name: disk free test

permissions:
  contents: write

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      - name: Check space before cleanup
        run: df -h
      - name: Cleaning
        run: |
          docker images
          sudo rm -rf "/opt/ghc" || true
          sudo rm -rf "/usr/share/dotnet" || true
          sudo rm -rf "$AGENT_TOOLSDIRECTORY" || true
          sudo rm -rf "/usr/local/lib/android" || true
          sudo rm -rf "/usr/local/share/boost" || true
          docker rmi $(docker image ls -q --filter "reference=node*")
          docker rmi $(docker image ls -q --filter "reference=debian*")
          docker rmi $(docker image ls -q --filter "reference=alpine*")
          docker rmi $(docker image ls -q --filter "reference=ubuntu:22.04")
      - name: apt-get remove cleanup
        run: |
          sudo apt-get remove --purge -y \
            ansible* \
            aria2* \
            aspnetcore* \
            azure-cli* \
            cabal* \
            clang* \
            dotnet-* \
            firefox* \
            gfortran-* \
            ghc* \
            google-chrome-stable* \
            google-cloud-sdk* \
            heroku* \
            imagemagick* \
            javascript* \
            kubectl* \
            llvm* \
            mono* \
            mysql* \
            nginx* \
            node* \
            npm* \
            nuget* \
            php* \
            postgresql* \
            powershell* \
            rpm* \
            ruby* \
            sqlite3* \
            subversion \
            temurin* \
            tmux* \
            vim* \
            yarn*
          sudo apt-get autoremove -y >/dev/null 2>&1 || true
          sudo apt-get autoclean -y >/dev/null 2>&1 || true
      - name: Check space after cleanup
        run: df -h
