name: main

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: Release target version
        type: string
        required: true

jobs:
  build_x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Get architecture
        id: get_arch
        run: |
          echo "Architecture: $(arch)"
          echo "arch=$(arch)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          echo "Input: ${{ github.event.inputs.target_version }}" > test_${{ steps.get_arch.outputs.arch }}".txt
          echo "Arch: ${{ steps.get_arch.outputs.arch }}" >> test_${{ steps.get_arch.outputs.arch }}".txt
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: built-glibc-bin
          path: test_${{ steps.get_arch.outputs.arch }}".txt
          retention-days: 1
  build_arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Set up qemu for arm64
        uses: docker/setup-qemu-action@v3
        with:
            platforms: linux/arm64
      - name: Get architecture
        id: get_arch
        run: |
          echo "Architecture: $(arch)"
          echo "arch=$(arch)" >> $GITHUB_OUTPUT
      - name: Build
        run: |
          echo "Input: ${{ github.event.inputs.target_version }}" > test_${{ steps.get_arch.outputs.arch }}".txt
          echo "Arch: ${{ steps.get_arch.outputs.arch }}" >> test_${{ steps.get_arch.outputs.arch }}".txt
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: built-glibc-bin
          path: test_${{ steps.get_arch.outputs.arch }}".txt
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [build_x86_64, build_arm64]
    steps:
      - name: Download archives
        uses: actions/download-artifact@v4
        with:
          pattern: test_*.txt
          merge-multiple: true
      - name: Show lists
        run: |
          ls -R
