name: main

permissions:
  contents: write

on:
  workflow_dispatch:
    inputs:
      target_version:
        description: Release target version
        type: string
        required: true

jobs:
  preparation:
    runs-on: ubuntu-latest
    steps:
      - name: CHeckout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Tag
        run: |
          git tag ${{ github.event.inputs.target_version }}
          git push origin ${{ github.event.inputs.target_version }}

  build_x86_64:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Build
        run: |
          echo "Input: ${{ github.event.inputs.target_version }}" > test_x86_64.txt
          echo "Arch: x86_64" >> test_x86_64.txt
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: test_x86_64.txt
          path: test_x86_64.txt
          retention-days: 1

  build_arm64:
    runs-on: ubuntu-latest
    needs: preparation
    steps:
      - name: Set up qemu for arm64
        uses: docker/setup-qemu-action@v3
        with:
            platforms: linux/arm64
      - name: Build
        run: |
          echo "Input: ${{ github.event.inputs.target_version }}" > test_arm64.txt
          docker run --platform linux/arm64 --rm -v $PWD:/app -w /app ubuntu arch > ARCH
          echo "Arch: $(cat ARCH)" >> test_arm64.txt
      - name: Archive build output
        uses: actions/upload-artifact@v4
        with:
          name: test_arm64.txt
          path: test_arm64.txt
          retention-days: 1

  release:
    runs-on: ubuntu-latest
    needs: [build_x86_64, build_arm64]
    steps:
      - name: Download archives
        uses: actions/download-artifact@v4
        with:
          pattern: test_*.txt
          merge-multiple: true
      - name: Show lists
        run: |
          ls -R
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.target_version }}
          body: |
            Test, version ${{ github.event.inputs.target_version }} for
            - arm64 (aarch64)
            - x86_64 (amd64)
          files: |
            test_x86_64.txt
            test_arm64.txt
